# Generated by Django 2.2.6 on 2019-11-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_firstname', models.CharField(max_length=25)),
                ('child_age_years', models.IntegerField(verbose_name='years old')),
                ('child_age_months', models.IntegerField(verbose_name='months old')),
                ('child_allergies', models.TextField(max_length=500)),
                ('child_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sit.Client')),
            ],
        ),
    ]
